language: dart
env:
  - SHARD=dartfmt
  - SHARD=test

install:
  - chmod 755 ./dev/bots/travis_install.sh
script:
  - chmod 755 ./dev/bots/travis_script.sh
after_success:
  - coveralls-lcov coverage/lcov.info